<!DOCTYPE html>
<html lang="en-US">
<head>

	<title>OpenWrt Forum Archive</title>

	<meta charset="UTF-8">

	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="assets/css/common.css">

</head>
<body>

<div class="container">

<header class="main-header">
	<h1 class="logo"><a href="index.html"><img src="assets/img/logo.png" width="376" height="88" alt="OpenWrt Forum Archive"></a></h1>
</header>

<aside>
	<p>This is a read-only archive of the old OpenWrt forum. The current OpenWrt forum resides at <a href="https://forum.openwrt.org/">https://forum.openwrt.org/</a>.</p>
	<p class="minor">In May 2018, the OpenWrt forum suffered a total data loss. This archive is an effort to restore and make available as much content as possible. Content may be missing or not representing the latest edited version.</p>
</aside>

<main>
	<header>
		<h1><span class="minor">Topic:</span> HLK-RM04 8MB Flash</h1>
	</header>
	<div class="notice minor">
		<p>
			The content of this topic has been archived
							on 11 Apr 2018.
										There are no obvious gaps in this topic, but there may still be some posts missing at the end.
					</p>
	</div>

	<div class="pagination"><div class="pagination-number">Page 1 of 1</div><nav><ul><li class="pagination-current"><span>1</span></li></ul></nav></div>
			
		
		
			<article class="post" id="p246471">
				<div class="post-metadata">
					<div class="post-num">Post #1</div>
					<div class="post-author">spanky</div>
					<div class="post-datetime">
						8 Sep 2014, 19:32					</div>
				</div>
				<div class="post-content content">
					<p>Hi-Link has started offering an 8MB flash, 32MB RAM module (I&#039;m not sure if its widely available yet, and there doesn&#039;t appear to be any easily identifiable physical differences - labeling and whatnot).</p><p>I had no problem identifying the 32MB of ram, but I am having difficulties making use of the additional flash space. I&#039;m compiling from the latest trunk.</p><p>If I add enough packages to the build, the sysupgrade file does not get built (it silently fails with &quot;too big&quot; error), so I&#039;m fairly certain this is a simple build/compile configuration issue, and probably also a definition issue somewhere in the source.</p><br /><p>I found this thread that seems to be of the same nature, but specific to another device:<br /><a href="https://forum.openwrt.org/viewtopic.php?id=32512">https://forum.openwrt.org/viewtopic.php?id=32512</a></p><p>and this one, again, specific to another piece of hardware, although fairly similar:<br /><a href="http://8devices.com/community/viewtopic.php?f=1&amp;t=386">http://8devices.com/community/viewtopic … &amp;t=386</a></p><br /><p>It looks like I need to modify the flash_layout layouts struct, but I dont know where to do this. &quot;target/linux/ramips/dts/HLKRM04.dts&quot; looks like a good place, but it does not specifically call out the rootfs or rootfd_data partitions, so I would imagine those are defined elsewhere, and not detected at runtime.</p><p>I also checked the kernel commandline and no mtdparts are defined there.</p><br /><br /><p>Here is the kernel log section where it identifies the 8MB flash, but does not extend rootfd_data to fill it:<br />It looks to be identifying the 8MB chip based on the boot log:<br />[&nbsp; &nbsp; 0.470000] m25p80 spi32766.0: found mx25l6405d, expected gd25q64<br />[&nbsp; &nbsp; 0.490000] m25p80 spi32766.0: mx25l6405d (8192 Kbytes)<br />[&nbsp; &nbsp; 0.500000] 4 ofpart partitions found on MTD device spi32766.0<br />[&nbsp; &nbsp; 0.510000] Creating 4 MTD partitions on &quot;spi32766.0&quot;:<br />[&nbsp; &nbsp; 0.520000] 0x000000000000-0x000000030000 : &quot;u-boot&quot;<br />[&nbsp; &nbsp; 0.540000] 0x000000030000-0x000000040000 : &quot;u-boot-env&quot;<br />[&nbsp; &nbsp; 0.540000] 0x000000040000-0x000000050000 : &quot;factory&quot;<br />[&nbsp; &nbsp; 0.570000] 0x000000050000-0x000000400000 : &quot;firmware&quot;<br />[&nbsp; &nbsp; 0.570000] 0x000000152014-0x000000400000 : &quot;rootfs&quot;<br />[&nbsp; &nbsp; 0.590000] mtd: partition &quot;rootfs&quot; must either start or end on erase block boundary or be smaller than an erase block -- forcing read-only<br />[&nbsp; &nbsp; 0.620000] mtd: device 4 (rootfs) set to be root filesystem<br />[&nbsp; &nbsp; 0.630000] mtd: partition &quot;rootfs_data&quot; created automatically, ofs=0x370000, len=0x90000<br />[&nbsp; &nbsp; 0.650000] 0x000000370000-0x000000400000 : &quot;rootfs_data&quot;</p><br /><br /><br /><p>Thoughts are greatly appreciated. Thanks!</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p246481">
				<div class="post-metadata">
					<div class="post-num">Post #2</div>
					<div class="post-author">wowbaggerHU</div>
					<div class="post-datetime">
						8 Sep 2014, 21:56					</div>
				</div>
				<div class="post-content content">
					<p>Hi spanky,</p><p>Now that you mention it, I remember that I had to edit the target/linux/ramips/image/Makefile:<br />line 430 should be<br />BuildFirmware/HLKRM04/squashfs=$(call BuildFirmware/Default8M/squashfs,$(1),$(2),$(3),$(4))<br />instead of:<br />BuildFirmware/HLKRM04/squashfs=$(call BuildFirmware/Default4M/squashfs,$(1),$(2),$(3),$(4))</p><p>Also, edit the target/linux/ramips/dts/HLKRM04.dts file:<br />for the firmware partition, edit the &quot;reg =&quot; line to show the following:<br />reg = &lt;0x50000 0x7b0000&gt;;</p><p>That should do the trick. (I&#039;m writing this based on my memories. If it still doesn&#039;t solve it for you, I&#039;ll boot my build VM, and take a closer look for you.)</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p246524">
				<div class="post-metadata">
					<div class="post-num">Post #3</div>
					<div class="post-author">spanky</div>
					<div class="post-datetime">
						9 Sep 2014, 09:21					</div>
				</div>
				<div class="post-content content">
					<p>I&#039;m recompiling with those changes. I previously tried editing the Default8M (without changing the firmware reg line) and had all kinds of boot errors. I think the reg line should do the trick. I&#039;ll let you know what happens.</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p246526">
				<div class="post-metadata">
					<div class="post-num">Post #4</div>
					<div class="post-author">spanky</div>
					<div class="post-datetime">
						9 Sep 2014, 10:12					</div>
				</div>
				<div class="post-content content">
					<p>Looks like those 2 changes did the trick. Thanks!</p><p># df -h<br />Filesystem&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Size&nbsp; &nbsp; &nbsp; Used Available Use% Mounted on<br />rootfs&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6.4M&nbsp; &nbsp; &nbsp;32.0K&nbsp; &nbsp; &nbsp; 6.4M&nbsp; &nbsp;0% /<br />/dev/root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;2.0M&nbsp; &nbsp; &nbsp; 2.0M&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;0 100% /rom<br />tmpfs&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;6.4M&nbsp; &nbsp; &nbsp;48.0K&nbsp; &nbsp; &nbsp; 6.4M&nbsp; &nbsp;1% /tmp<br />tmpfs&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;6.4M&nbsp; &nbsp; &nbsp;32.0K&nbsp; &nbsp; &nbsp; 6.4M&nbsp; &nbsp;0% /tmp/root<br />overlayfs:/tmp/root&nbsp; &nbsp; &nbsp; &nbsp;6.4M&nbsp; &nbsp; &nbsp;32.0K&nbsp; &nbsp; &nbsp; 6.4M&nbsp; &nbsp;0% /<br />tmpfs&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;512.0K&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;0&nbsp; &nbsp; 512.0K&nbsp; &nbsp;0% /dev</p><br /><p>Now I just need to figure out how to compile uboot to turn off the serial port...</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p246527">
				<div class="post-metadata">
					<div class="post-num">Post #5</div>
					<div class="post-author">wowbaggerHU</div>
					<div class="post-datetime">
						9 Sep 2014, 10:23					</div>
				</div>
				<div class="post-content content">
					<p>I&#039;m glad, that it worked for you.<br />Can&#039;t help you with u-boot compilation though.</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p246533">
				<div class="post-metadata">
					<div class="post-num">Post #6</div>
					<div class="post-author">FrankW</div>
					<div class="post-datetime">
						9 Sep 2014, 12:41					</div>
				</div>
				<div class="post-content content">
					<p>&gt; Hi-Link has started offering an 8MB flash, 32MB RAM module <br />&gt; (I&#039;m not sure if its widely available yet,</p><p>Could you give us a link or some other information where you found this new 8MB/32MB module ?</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p246550">
				<div class="post-metadata">
					<div class="post-num">Post #7</div>
					<div class="post-author">spanky</div>
					<div class="post-datetime">
						9 Sep 2014, 17:04					</div>
				</div>
				<div class="post-content content">
					<p>Aliexpress. I emailed the seller (hlktech) and asked for the larger chip.</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p246555">
				<div class="post-metadata">
					<div class="post-num">Post #8</div>
					<div class="post-author">spanky</div>
					<div class="post-datetime">
						9 Sep 2014, 17:15					</div>
				</div>
				<div class="post-content content">
					<p>Oh, it looks like they posted it as the HLK-RM04-E</p><br /><p><a href="http://www.aliexpress.com/store/product/Uart-to-wifi-Converter-with-32M-Ram-8M-Flash-Embedded-WiFi-Module/345286_1933230857.html">http://www.aliexpress.com/store/product … 30857.html</a></p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p246568">
				<div class="post-metadata">
					<div class="post-num">Post #9</div>
					<div class="post-author">spanky</div>
					<div class="post-datetime">
						9 Sep 2014, 20:23					</div>
				</div>
				<div class="post-content content">
					<p>I guess I spoke too soon.... I recompiled a couple of times (I forgot to add mem=32M on the kernel commandline, but thats a separate issue). I added enough packages to bust through the 4M firmware image size, and heres what I have now:</p><p># df -h<br />Filesystem&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Size&nbsp; &nbsp; &nbsp; Used Available Use% Mounted on<br />rootfs&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;14.3M&nbsp; &nbsp; &nbsp;44.0K&nbsp; &nbsp; &nbsp;14.3M&nbsp; &nbsp;0% /<br />/dev/root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;4.0M&nbsp; &nbsp; &nbsp; 4.0M&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;0 100% /rom &lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;<br />tmpfs&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 14.3M&nbsp; &nbsp; &nbsp;52.0K&nbsp; &nbsp; &nbsp;14.3M&nbsp; &nbsp;0% /tmp<br />tmpfs&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 14.3M&nbsp; &nbsp; &nbsp;44.0K&nbsp; &nbsp; &nbsp;14.3M&nbsp; &nbsp;0% /tmp/root<br />overlayfs:/tmp/root&nbsp; &nbsp; &nbsp; 14.3M&nbsp; &nbsp; &nbsp;44.0K&nbsp; &nbsp; &nbsp;14.3M&nbsp; &nbsp;0% / &lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;<br />tmpfs&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;512.0K&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;0&nbsp; &nbsp; 512.0K&nbsp; &nbsp;0% /dev</p><p>My sysupgrade image is ~5MB, but it seems that /dev/root is limited to 4MB. </p><p>The overlay is coming from tmpfs (i.e. not the remaining part of the flash). overlay should be less than 4MB.</p><p>(Note: it worked fine with mem=32, but the image size &lt;4MB)</p><br /><br /><p>I dont know where the boundary between rootfs and rootfs_data on the MTD is defined, but that seems like the issue.</p><br /><br /><p>heres the kernel log:<br />[&nbsp; &nbsp; 0.470000] m25p80 spi32766.0: found mx25l6405d, expected gd25q64<br />[&nbsp; &nbsp; 0.490000] m25p80 spi32766.0: mx25l6405d (8192 Kbytes)<br />[&nbsp; &nbsp; 0.490000] 4 ofpart partitions found on MTD device spi32766.0<br />[&nbsp; &nbsp; 0.510000] Creating 4 MTD partitions on &quot;spi32766.0&quot;:<br />[&nbsp; &nbsp; 0.520000] 0x000000000000-0x000000030000 : &quot;u-boot&quot;<br />[&nbsp; &nbsp; 0.530000] 0x000000030000-0x000000040000 : &quot;u-boot-env&quot;<br />[&nbsp; &nbsp; 0.550000] 0x000000040000-0x000000050000 : &quot;factory&quot;<br />[&nbsp; &nbsp; 0.560000] 0x000000050000-0x000000800000 : &quot;firmware&quot;<br />[&nbsp; &nbsp; 0.580000] 0x0000001504f1-0x000000800000 : &quot;rootfs&quot;<br />[&nbsp; &nbsp; 0.580000] mtd: partition &quot;rootfs&quot; must either start or end on erase block boundary or be smaller than an erase block -- forcing read-only<br />[&nbsp; &nbsp; 0.620000] mtd: device 4 (rootfs) set to be root filesystem<br />[&nbsp; &nbsp; 0.620000] mtd: partition &quot;rootfs_data&quot; created automatically, ofs=0x520000, len=0x2e0000<br />[&nbsp; &nbsp; 0.650000] 0x000000520000-0x000000800000 : &quot;rootfs_data&quot;</p><br /><p>I&#039;m no expert, but it looks to me like the kernel is detecting the boundry, but further down the line when mounting, something goes amiss. I could be completely off on that.</p><br /><br /><p>Heres the /proc/mtd, if that offers any clues:</p><p># cat /proc/mtd<br />dev:&nbsp; &nbsp; size&nbsp; &nbsp;erasesize&nbsp; name<br />mtd0: 00030000 00010000 &quot;u-boot&quot;<br />mtd1: 00010000 00010000 &quot;u-boot-env&quot;<br />mtd2: 00010000 00010000 &quot;factory&quot;<br />mtd3: 007b0000 00010000 &quot;firmware&quot;<br />mtd4: 006afb0f 00010000 &quot;rootfs&quot;<br />mtd5: 002e0000 00010000 &quot;rootfs_data&quot;</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p246635">
				<div class="post-metadata">
					<div class="post-num">Post #10</div>
					<div class="post-author">FrankW</div>
					<div class="post-datetime">
						10 Sep 2014, 14:07					</div>
				</div>
				<div class="post-content content">
					<div class="quotebox"><cite>spanky wrote:</cite><blockquote><p>Oh, it looks like they posted it as the HLK-RM04-E<br />....</p></blockquote></div><p>I sent a mail to HlkTech and asked where to get it. <br />It&#039;s now available in the <a href="http://www.hlktech.net/product_detail.php?ProId=49">HLK Webshop</a> as well.</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p247653">
				<div class="post-metadata">
					<div class="post-num">Post #11</div>
					<div class="post-author">baylf2000</div>
					<div class="post-datetime">
						21 Sep 2014, 10:36					</div>
				</div>
				<div class="post-content content">
					<p>Just a thought, and I&#039;m definitely no expert, but have you tried using one of the other RT5350 images, from a system which already has 32M and 8M? I upgraded the ram to 32M on the HLK-RM04 modules I have, and to save having to recompile the kernel I use the MPRA2 images, which work perfectly.</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p250062">
				<div class="post-metadata">
					<div class="post-num">Post #12</div>
					<div class="post-author">FrankW</div>
					<div class="post-datetime">
						10 Oct 2014, 21:47					</div>
				</div>
				<div class="post-content content">
					<p>I guess, I need some help.<br />I got the module today.</p><p>I Changed <br />-&nbsp; firmware partition to reg = &lt;0x50000 0x7b0000&gt;;&nbsp; &nbsp;in the DTS file<br />-&nbsp; BuildFirmware/HLKRM04/squashfs=$(call BuildFirmware/Default8M/squashfs,$(1),$(2),$(3),$(4))&nbsp; &nbsp;int the Makefile. <br />and recompiled it.<br />Installed the uboot256 and uploaded the openwrt-ramips-rt305x-hlk-rm04-initramfs-uImage.bin&nbsp; &nbsp; <br />&nbsp; &nbsp; &nbsp;( 2: Load system code then write to Flash via TFTP. ) </p><p>It boots - and everything looks fine - at first. <br />But when I reboot the HLK, is just says : <br /></p><div class="codebox"><pre><code>## Booting image at bc050000 ...
raspi_read: from:50000 len:40
.   Image Name:   HLK-RM02
   Created:      2014-10-10  17:45:46 UTC
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    994304 Bytes = 971 kB
   Load Address: 80000000
   Entry Point:  80000000
raspi_read: from:50040 len:f2c00
................   Verifying Checksum ... OK
   Uncompressing Kernel Image ... OK
No initrd
## Transferring control to Linux (at address 80000000) ...
## Giving linux memsize in MB, 32

Starting kernel ...</code></pre></div><p> <br />and that&#039;s it. Systems apparently stops.</p><br /><br /><p>Directly after uploading it with TFTP - when it&#039;s working - it says<br /></p><div class="codebox"><pre><code> 
## Booting image at bc050000 ...
raspi_read: from:50000 len:40
.   Image Name:   HLK-RM02
   Created:      2014-10-10  17:45:46 UTC
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    994304 Bytes = 971 kB
   Load Address: 80000000
   Entry Point:  80000000
raspi_read: from:50040 len:f2c00
................   Verifying Checksum ... OK
   Uncompressing Kernel Image ... OK
No initrd
## Transferring control to Linux (at address 80000000) ...
## Giving linux memsize in MB, 32

Starting kernel ...

[    0.000000] Linux version 3.10.49 (root@walle1.tklinux.de) (gcc version 4.8.3 (OpenWrt/Linaro GCC 4.8-2014.04 r42162) ) #33 Fri Oct 10 19:44:50 CEST 2014
[    0.000000] SoC Type: Ralink RT5350 id:1 rev:3
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU revision is: 0001964c (MIPS 24KEc) 
[    0.000000] MIPS: machine is HILINK HLK-RM04        
[    0.000000] Determined physical RAM map:               
[    0.000000]  memory: 02000000 @ 00000000 (usable)                                                                
[    0.000000] User-defined physical RAM map:       
[    0.000000]  memory: 02000000 @ 00000000 (usable)                                                                                                              
[    0.000000] Initrd not found or empty - disabling initrd 
[    0.000000] Zone ranges:                                            
[    0.000000]   Normal   [mem 0x00000000-0x01ffffff]  
[    0.000000] Movable zone start for each node               
[    0.000000] Early memory node ranges                        
[    0.000000]   node   0: [mem 0x00000000-0x01ffffff] 
[    0.000000] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes. 
[    0.000000] Primary data cache 16kB, 4-way, VIPT, no aliases, linesize 32 bytes
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 8128
[    0.000000] Kernel command line: rootfstype=squashfs,jffs2 mem=32M console=ttyS1,57600
[    0.000000] PID hash table entries: 128 (order: -3, 512 bytes)
[    0.000000] Dentry cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Inode-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000000] Writing ErrCtl register=00004447
[    0.000000] Readback ErrCtl register=00004447
[    0.000000] Memory: 29352k/32768k available (2133k kernel code, 3416k reserved, 543k data, 200k init, 0k highmem)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS:256
[    0.000000] CPU Clock: 360MHz
[    0.000000] Calibrating delay loop... 239.61 BogoMIPS (lpj=1198080)
[    0.070000] pid_max: default: 32768 minimum: 301
[    0.070000] Mount-cache hash table entries: 512
[    0.080000] pinctrl core: initialized pinctrl subsystem 
[    0.090000] NET: Registered protocol family 16   
[    0.110000] rt2880-pinmux pinctrl.1: invalid group &quot;JTAG&quot; for function &quot;gpio&quot;
[    0.140000] bio: create slab &lt;bio-0&gt; at 0
[    0.150000] rt2880_gpio 10000600.gpio: registering 24 gpios
[    0.160000] rt2880_gpio 10000600.gpio: registering 24 irq handlers
[    0.170000] rt2880_gpio 10000660.gpio: registering 6 gpios
[    0.180000] rt2880_gpio 10000660.gpio: registering 6 irq handlers
[    0.190000] Switching to clocksource MIPS        
[    0.200000] NET: Registered protocol family 2    
[    0.210000] TCP established hash table entries: 512 (order: 0, 4096 bytes)
[    0.230000] TCP bind hash table entries: 512 (order: -1, 2048 bytes)
[    0.240000] TCP: Hash tables configured (established 512 bind 512)
[    0.250000] TCP: reno registered
[    0.260000] UDP hash table entries: 256 (order: 0, 4096 bytes) 
[    0.270000] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.280000] NET: Registered protocol family 1
[    0.290000] rt-timer 10000100.timer: maximum frequncy is 7324Hz 
[    0.350000] squashfs: version 4.0 (2009/01/31) Phillip Lougher        
[    0.360000] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.380000] msgmni has been set to 57
[    0.390000] io scheduler noop registered
[    0.400000] io scheduler deadline registered (default)
[    0.410000] Serial: 8250/16550 driver, 2 ports, IRQ sharing disabled 
[    0.430000] 10000500.uart: ttyS0 at MMIO 0x10000500 (irq = 13) is a 16550A
[    0.440000] 10000c00.uartlite: ttyS1 at MMIO 0x10000c00 (irq = 20) is a 16550A
[    0.460000] console [ttyS1] enabled, bootconsole disabled
[    0.460000] console [ttyS1] enabled, bootconsole disabled
[    0.490000] m25p80 spi32766.0: found mx25l6405d, expected gd25q64
[    0.500000] m25p80 spi32766.0: mx25l6405d (8192 Kbytes)
[    0.510000] 4 ofpart partitions found on MTD device spi32766.0
[    0.520000] Creating 4 MTD partitions on &quot;spi32766.0&quot;: 
[    0.530000] 0x000000000000-0x000000030000 : &quot;u-boot&quot;
[    0.550000] 0x000000030000-0x000000040000 : &quot;u-boot-env&quot;
[    0.560000] 0x000000040000-0x000000050000 : &quot;factory&quot;
[    0.580000] 0x000000050000-0x000000800000 : &quot;firmware&quot;
[    0.590000] 0x000000142c40-0x000000800000 : &quot;rootfs&quot;
[    0.600000] mtd: partition &quot;rootfs&quot; must either start or end on erase block boundary or be smaller than an erase block -- forcing read-only
[    0.630000] mtd: device 4 (rootfs) set to be root filesystem
[    0.640000] mtd: partition &quot;rootfs_data&quot; created automatically, ofs=0x380000, len=0x480000 
[    0.660000] 0x000000380000-0x000000800000 : &quot;rootfs_data&quot;
[    0.680000] eth0: done loading                                
[    0.690000] rt2880_wdt 10000120.watchdog: Initialized
[    0.700000] TCP: cubic registered                                  
......
[   15.020000] rt305x-esw 10110000.esw: link changed 0x00
[   16.750000] rt305x-esw 10110000.esw: link changed 0x08
[   17.510000] jffs2_scan_eraseblock(): End of filesystem marker found at 0x0
[   17.550000] jffs2_build_filesystem(): unlocking the mtd device... done.
[   17.560000] jffs2_build_filesystem(): erasing all blocks after the end marker... [   20.440000] device eth0.1 entered promiscuous mode 
[   20.450000] device eth0 entered promiscuous mode 
[   20.480000] br-lan: port 1(eth0.1) entered forwarding state
[   20.490000] br-lan: port 1(eth0.1) entered forwarding state
[   22.490000] br-lan: port 1(eth0.1) entered forwarding state
done.
[   63.800000] jffs2: notice: (602) jffs2_build_xattr_subsystem: complete building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0 .
procd:  - init complete - </code></pre></div><p> </p><p>/proc/mtd says : <br /></p><div class="codebox"><pre><code> 
dev:    size   erasesize  name                    
mtd0: 00030000 00010000 &quot;u-boot&quot;      
mtd1: 00010000 00010000 &quot;u-boot-env&quot;
mtd2: 00010000 00010000 &quot;factory&quot;      
mtd3: 007b0000 00010000 &quot;firmware&quot;   
mtd4: 006bd3c0 00010000 &quot;rootfs&quot;        
mtd5: 00480000 00010000 &quot;rootfs_data&quot;</code></pre></div><p> </p><br /><p>df -h says <br /></p><div class="codebox"><pre><code> 
Filesystem                Size      Used Available Use% Mounted on
rootfs                    4.5M    268.0K      4.2M   6% /                  
/dev/root                 2.3M      2.3M         0 100% /rom            
tmpfs                    14.4M     48.0K     14.4M   0% /tmp          
tmpfs                    14.4M     20.0K     14.4M   0% /tmp/root   
tmpfs                   512.0K         0    512.0K   0% /dev             
/dev/mtdblock5            4.5M    268.0K      4.2M   6% /overlay 
overlayfs:/overlay        4.5M    268.0K      4.2M   6% /       </code></pre></div><br /><p>Interesting is maybe : <br />[&nbsp; &nbsp; 0.490000] m25p80 spi32766.0: found mx25l6405d, expected gd25q64<br />[&nbsp; &nbsp; 0.500000] m25p80 spi32766.0: mx25l6405d (8192 Kbytes)</p><p>Any ideas what could be wrong here, and why it won&#039;t boot ? </p><br /><p>Thanks<br />FrankW</p>											<p class="post-edited">(Last edited by <strong>FrankW</strong> on 10 Oct 2014, 22:02)</p>
									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p250204">
				<div class="post-metadata">
					<div class="post-num">Post #13</div>
					<div class="post-author">wowbaggerHU</div>
					<div class="post-datetime">
						12 Oct 2014, 12:59					</div>
				</div>
				<div class="post-content content">
					<p>Hi,</p><p>Did you edit the kernel command line?<br />What does it say in the .dts file? Did you happen to edit the kernel commandline in &quot;make kernel_menuconfig&quot;?</p><p>It seems suspicious to me, that there is no output. If the commandline doesn&#039;t tell the kernel where to print the boot messages, they won&#039;t show up on the serial console.<br />Btw, does it work after a &quot;cold&quot; reboot, or does it fail in that case as well? Alas, does it only boot once, after it has been written to flash?</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p250490">
				<div class="post-metadata">
					<div class="post-num">Post #14</div>
					<div class="post-author">FrankW</div>
					<div class="post-datetime">
						14 Oct 2014, 10:22					</div>
				</div>
				<div class="post-content content">
					<p>Hi,</p><p>thank you for your reply.</p><p>I don&#039;t really know what the problem was, but I have a working system now. <br />I simply downloaded a new TRUNK, made the necessary changes for 8MB Flash and 32MB Ram,<br />and it is working !! Perfect. <br />I don&#039;t know what went wrong with the old version I used - but anyway. I have a working <br />system.</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p260677">
				<div class="post-metadata">
					<div class="post-num">Post #15</div>
					<div class="post-author">pingo</div>
					<div class="post-datetime">
						9 Jan 2015, 10:46					</div>
				</div>
				<div class="post-content content">
					<p>Hello.</p><p>Are the described steps still necessary for the 8MB flash/32MB ram version or is there a precompiled image available from openwrt? </p><p>All I&#039;ve found was <a href="https://downloads.openwrt.org/snapshots/trunk/ramips/openwrt-ramips-rt305x-hlk-rm04-squashfs-sysupgrade.bin">https://downloads.openwrt.org/snapshots … pgrade.bin</a></p>									</div>
			</article>

			
		
	
			<div class="notice minor">
			<p>The discussion might have continued from here.</p>
		</div>
	
	<div class="pagination"><div class="pagination-number">Page 1 of 1</div><nav><ul><li class="pagination-current"><span>1</span></li></ul></nav></div>
</main>

</div>


<!-- Created in a hurry and not indicative of usual code quality. Here's a number: 0 -->

</body>
</html>